import Header from '@/components/screens/Layout/Header/Header'
import MainProvider from '@/provider/MainProvider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './layout.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<MainProvider>
					<div className={styles.container}>
						<Header />
						{children}
					</div>
				</MainProvider>
			</body>
		</html>
	)
}
